# Setup
title:               blank
tagline:             ''
description:         ''
url:                 http://vilsaira.github.io
baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Viljami Sairanen
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: 
